/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.launchcode.temperature.test;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;
import org.launchcode.temperature.Scale;
import org.launchcode.temperature.Temperature;
import org.launchcode.temperature.TemperatureConversionException;

public class TemperatureTest {
    private Temperature absoluteZero;
    private Temperature freezing;
    private Temperature boiling;

    @Before
    public void setUp() {
        absoluteZero = new Temperature(0, Scale.KELVIN);
        try {
            freezing = new Temperature(0, Scale.CELSIUS);
            boiling = new Temperature(100, Scale.CELSIUS);
        } catch (TemperatureConversionException ex) {
            ex.printStackTrace();
            System.exit(1);
        }
    }

    @Test
    public void testFreezing() {
        Temperature freezingF = new Temperature(32, Scale.FAHRENHEIT);
        assertEquals(freezing.getDegrees(), freezingF.toCelsius().getDegrees(), 0.01);
    }

    @Test
    public void testBoiling() {
        Temperature boilingF = new Temperature(212, Scale.FAHRENHEIT);
        assertEquals(boiling.getDegrees(), boilingF.toCelsius().getDegrees(), 0.01);
    }
}
